[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.network.egress]]
host = "smtp.gmail.com"
protocol = "tcp"
ports = [25, 465, 587]

[[deploy.network.egress]]
host = "142.250.4.108"
protocol = "tcp"
ports = [25, 465, 587]

[[deploy.network.egress]]
host = "142.251.31.108"
protocol = "tcp" 
ports = [25, 465, 587]